local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node
local d = ls.dynamic_node
local sn = ls.snippet_node

-- luasnip snippet for LaTeX template
return {
  s("classart", {
    t({
      "\\documentclass{article}",
      "",
      "\\usepackage{amssymb}",
      "\\usepackage{amsmath}",
      "\\usepackage{amsthm}",
      "\\usepackage[margin=0.5in]{geometry}",
      "\\usepackage{amsfonts}",
      "\\usepackage{graphicx, overpic}",
      "\\usepackage{color}",
      "\\usepackage{enumerate}",
      "\\usepackage{multicol}",
      "\\usepackage{mathrsfs}",
      "\\usepackage{mathabx}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage{setspace}",
      "\\usepackage{enumitem}",
      "\\usepackage{minted}",
      "",
      "% Theorem Environments",
      "\\theoremstyle{plain}",
      "\\newtheorem{thm}{Theorem}[section]",
      "\\newtheorem{lemma}[thm]{Lemma}",
      "\\newtheorem{sublemma}[thm]{Sub-Lemma}",
      "\\newtheorem{prop}[thm]{Proposition}",
      "\\newtheorem{corollary}[thm]{Corollary}",
      "",
      "% Definition Environments",
      "\\theoremstyle{definition}",
      "\\newtheorem*{defn}{Definition}",
      "\\newtheorem*{example}{Example}",
      "\\newtheorem*{remark}{Remark}",
      "\\newtheorem*{examples}{Examples}",
      "\\newtheorem*{obs}{Observation}",
      "\\newtheorem*{claim}{Claim}",
      "\\newtheorem*{assumption}{Assumption}",
      "\\newtheorem*{notation}{Notation}",
      "\\newtheorem*{counter}{Counterexample}",
      "",
      "% Logic ",
      "\\newcommand{\\sat}{\\vDash}",
      "\\newcommand{\\unsat}{\\nvDash}",
      "\\renewcommand{\\iff}{\\leftrightarrow}",
      "\\renewcommand{\\implies}{\\rightarrow}",
      "",
      "% Mathbb",
      "\\newcommand{\\Z}{\\mathbb{Z}}",
      "\\newcommand{\\R}{\\mathbb{R}}",
      "\\newcommand{\\N}{\\mathbb{N}}",
      "\\newcommand{\\Q}{\\mathbb{Q}}",
      "\\newcommand{\\F}{\\mathbb{F}}",
      "\\newcommand{\\C}{\\mathbb{C}}",
      "",
      "% Mathcal",
      "\\newcommand{\\cA}{\\mathcal{A}}",
      "\\newcommand{\\cB}{\\mathcal{B}}",
      "\\newcommand{\\cC}{\\mathcal{C}}",
      "\\newcommand{\\cD}{\\mathcal{D}}",
      "\\newcommand{\\cE}{\\mathcal{E}}",
      "\\newcommand{\\cF}{\\mathcal{F}}",
      "\\newcommand{\\cG}{\\mathcal{G}}",
      "\\newcommand{\\cH}{\\mathcal{H}}",
      "\\newcommand{\\cI}{\\mathcal{I}}",
      "\\newcommand{\\cJ}{\\mathcal{J}}",
      "\\newcommand{\\cK}{\\mathcal{K}}",
      "\\newcommand{\\cL}{\\mathcal{L}}",
      "\\newcommand{\\cM}{\\mathcal{M}}",
      "\\newcommand{\\cN}{\\mathcal{N}}",
      "\\newcommand{\\cO}{\\mathcal{O}}",
      "\\newcommand{\\cP}{\\mathcal{P}}",
      "\\newcommand{\\cQ}{\\mathcal{Q}}",
      "\\newcommand{\\cR}{\\mathcal{R}}",
      "\\newcommand{\\cS}{\\mathcal{S}}",
      "\\newcommand{\\cT}{\\mathcal{T}}",
      "\\newcommand{\\cU}{\\mathcal{U}}",
      "\\newcommand{\\cV}{\\mathcal{V}}",
      "\\newcommand{\\cW}{\\mathcal{W}}",
      "\\newcommand{\\cX}{\\mathcal{X}}",
      "\\newcommand{\\cY}{\\mathcal{Y}}",
      "\\newcommand{\\cZ}{\\mathcal{Z}}",
      "",
      "% Greek",
      "\\newcommand{\\gt}{\\theta}",
      "\\newcommand{\\gT}{\\Theta}",
      "\\newcommand{\\gl}{\\lambda}",
      "\\newcommand{\\go}{\\omega}",
      "\\newcommand{\\gO}{\\Omega}",
      "",
      "% Brackets",
      "\\newcommand{\\la}{\\langle}",
      "\\newcommand{\\ra}{\\rangle}",
      "\\newcommand{\\lb}{\\{}",
      "\\newcommand{\\rb}{\\}}",
      "\\newcommand{\\lp}{\\left(}",
      "\\newcommand{\\rp}{\\right)}",
      "",
      "% Signs",
      "\\newcommand{\\lar}{\\leftarrow}",
      "\\newcommand{\\rar}{\\rightarrow}",
      "\\newcommand{\\lrar}{\\leftrightarrow}",
      "",
      "\\title{", }),
    i(1, "Title"),
    t({"}", "\\author{"}),
    i(2, "Author"),
    t({"}", "\\date{\\today}", "", "\\begin{document}", "\\maketitle", "", ""}),
    i(0),
    t({"", "\\end{document}"}),
  }),
}
